use_frameworks!
platform :ios, '11.0'

target 'HomeTime' do
  # Pods for HomeTime
  pod 'RxSwift', '~> 5'
  pod 'RxRelay', '~> 5'
  
  target 'HomeTimeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 2.2'
    pod 'Nimble', '~> 8.0'
  end

end
